default:
  image: nikolaik/python-nodejs:python3.9-nodejs16
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - poetry install

django-migrations:
  stage: build
  script:
    - python3 manage.py migrate
    - python3 manage.py check

tests:
  stage: test
  script:
    - pytest -v

deploy:
  stage: deploy
  script:
    - echo "TODO run the fabric script"