# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: pipenv run black
    exclude: model_config.py
    args: [--check]
    language: system
    require_serial: true
    types: [python]
  - id: isort
    name: isort
    entry: pipenv run isort
    args: [--check-only]
    language: system
    types: [python]
