version: '3'
services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: bbs

        ports:
            - "3306:3306"
        volumes:
            - mydata:/var/lib/mysql

networks:
    default:
        driver: bridge

volumes:
    mydata:
