# Generated by Django 4.0.2 on 2022-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="amount",
            field=models.IntegerField(verbose_name="Antall"),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="unit_price",
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name="Enhetspris"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name="Enhetspris"),
        ),
        migrations.AlterField(
            model_name="product",
            name="alcohol_percent",
            field=models.DecimalField(decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price_ext",
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price_int",
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name="product",
            name="volume_liter",
            field=models.DecimalField(decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
